# Generated by Django 3.2.24 on 2024-02-13 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': [], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
