# Generated by Django 3.2.24 on 2024-02-13 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': [], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
