# Generated by Django 3.2.24 on 2024-02-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='price',
        ),
        migrations.AddField(
            model_name='sku',
            name='cost_price',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='platform_commission',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, help_text='Price payable by customer (Rs.)', max_digits=10, null=True, verbose_name='selling price (Rs.)'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='size',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
