# Generated by Django 3.2.24 on 2024-02-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20240224_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.CharField(blank=True, help_text='Add new ingredients ', max_length=500, null=True),
        ),
    ]
