# Generated by Django 3.2.24 on 2024-02-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price payable by customer (Rs.)', max_digits=10, null=True, verbose_name='selling price (Rs.)'),
        ),
    ]
