# Generated by Django 3.2.24 on 2024-02-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_sku_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='size',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Size and quantity of the products in gms'),
        ),
    ]
