# Generated by Django 3.2.24 on 2024-02-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_sku_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveSmallIntegerField(help_text='Price payable by customer (Rs.)', null=True, verbose_name='selling price (Rs.)'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='cost_price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sku',
            name='platform_commission',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
