# Generated by Django 3.2.24 on 2024-02-26 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_price'),
    ]

    operations = [
    ]
