# Generated by Django 3.2.24 on 2024-02-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20240226_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveSmallIntegerField(help_text='Price payable by customer (Rs.)', null=True, verbose_name='selling price (Rs.)'),
        ),
    ]
