# Generated by Django 3.2.24 on 2024-02-26 04:57

from django.db import migrations


def transfer_price_to_selling_price(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    Sku = apps.get_model('products', 'Sku')
    Sku.objects.filter(size=None).update(size=0)

    for product in Product.objects.all():
        sku = Sku.objects.create(product=product, selling_price=product.price,size=0)

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_price'),
    ]

    operations = [
        migrations.RunPython(transfer_price_to_selling_price)
    ]
