# Generated by Django 3.2.24 on 2024-02-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20240226_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='mesurement_unit',
            field=models.IntegerField(choices=[(1, 'gm'), (2, 'kg'), (3, 'ml'), (4, 'L'), (5, 'pc')], null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending for approval'), (2, 'Approved'), (3, 'Discontinued')], default=1, null=True),
        ),
        migrations.AddConstraint(
            model_name='sku',
            constraint=models.CheckConstraint(check=models.Q(('size__lte', 999)), name='size_limit'),
        ),
    ]
