# Generated by Django 3.2.24 on 2024-02-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20240226_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='mesurement_unit',
            field=models.IntegerField(choices=[(1, 'gm'), (2, 'kg'), (3, 'ml'), (4, 'L'), (5, 'pc')], default=1),
        ),
    ]
